//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the gazebo_mecanum_plugins package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __gazebo_mecanum_plugins__GAZEBO_MECANUM_PLUGINS_PIDCONFIG_H__
#define __gazebo_mecanum_plugins__GAZEBO_MECANUM_PLUGINS_PIDCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace gazebo_mecanum_plugins
{
  class gazebo_mecanum_plugins_pidConfigStatics;

  class gazebo_mecanum_plugins_pidConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(gazebo_mecanum_plugins_pidConfig &config, const gazebo_mecanum_plugins_pidConfig &max, const gazebo_mecanum_plugins_pidConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const gazebo_mecanum_plugins_pidConfig &config1, const gazebo_mecanum_plugins_pidConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, gazebo_mecanum_plugins_pidConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const gazebo_mecanum_plugins_pidConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, gazebo_mecanum_plugins_pidConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const gazebo_mecanum_plugins_pidConfig &config) const = 0;
      virtual void getValue(const gazebo_mecanum_plugins_pidConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T gazebo_mecanum_plugins_pidConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T gazebo_mecanum_plugins_pidConfig::* field;

      virtual void clamp(gazebo_mecanum_plugins_pidConfig &config, const gazebo_mecanum_plugins_pidConfig &max, const gazebo_mecanum_plugins_pidConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const gazebo_mecanum_plugins_pidConfig &config1, const gazebo_mecanum_plugins_pidConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, gazebo_mecanum_plugins_pidConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const gazebo_mecanum_plugins_pidConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, gazebo_mecanum_plugins_pidConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const gazebo_mecanum_plugins_pidConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const gazebo_mecanum_plugins_pidConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, gazebo_mecanum_plugins_pidConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, gazebo_mecanum_plugins_pidConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<gazebo_mecanum_plugins_pidConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(gazebo_mecanum_plugins_pidConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("LEFT_REAR_P"==(*_i)->name){LEFT_REAR_P = boost::any_cast<double>(val);}
        if("LEFT_REAR_I"==(*_i)->name){LEFT_REAR_I = boost::any_cast<double>(val);}
        if("LEFT_REAR_D"==(*_i)->name){LEFT_REAR_D = boost::any_cast<double>(val);}
        if("LEFT_FRONT_P"==(*_i)->name){LEFT_FRONT_P = boost::any_cast<double>(val);}
        if("LEFT_FRONT_I"==(*_i)->name){LEFT_FRONT_I = boost::any_cast<double>(val);}
        if("LEFT_FRONT_D"==(*_i)->name){LEFT_FRONT_D = boost::any_cast<double>(val);}
        if("RIGHT_FRONT_P"==(*_i)->name){RIGHT_FRONT_P = boost::any_cast<double>(val);}
        if("RIGHT_FRONT_I"==(*_i)->name){RIGHT_FRONT_I = boost::any_cast<double>(val);}
        if("RIGHT_FRONT_D"==(*_i)->name){RIGHT_FRONT_D = boost::any_cast<double>(val);}
        if("RIGHT_REAR_P"==(*_i)->name){RIGHT_REAR_P = boost::any_cast<double>(val);}
        if("RIGHT_REAR_I"==(*_i)->name){RIGHT_REAR_I = boost::any_cast<double>(val);}
        if("RIGHT_REAR_D"==(*_i)->name){RIGHT_REAR_D = boost::any_cast<double>(val);}
      }
    }

    double LEFT_REAR_P;
double LEFT_REAR_I;
double LEFT_REAR_D;
double LEFT_FRONT_P;
double LEFT_FRONT_I;
double LEFT_FRONT_D;
double RIGHT_FRONT_P;
double RIGHT_FRONT_I;
double RIGHT_FRONT_D;
double RIGHT_REAR_P;
double RIGHT_REAR_I;
double RIGHT_REAR_D;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LEFT_REAR_P;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LEFT_REAR_I;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LEFT_REAR_D;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LEFT_FRONT_P;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LEFT_FRONT_I;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LEFT_FRONT_D;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double RIGHT_FRONT_P;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double RIGHT_FRONT_I;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double RIGHT_FRONT_D;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double RIGHT_REAR_P;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double RIGHT_REAR_I;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double RIGHT_REAR_D;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("gazebo_mecanum_plugins_pidConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const gazebo_mecanum_plugins_pidConfig &__max__ = __getMax__();
      const gazebo_mecanum_plugins_pidConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const gazebo_mecanum_plugins_pidConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const gazebo_mecanum_plugins_pidConfig &__getDefault__();
    static const gazebo_mecanum_plugins_pidConfig &__getMax__();
    static const gazebo_mecanum_plugins_pidConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const gazebo_mecanum_plugins_pidConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void gazebo_mecanum_plugins_pidConfig::ParamDescription<std::string>::clamp(gazebo_mecanum_plugins_pidConfig &config, const gazebo_mecanum_plugins_pidConfig &max, const gazebo_mecanum_plugins_pidConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class gazebo_mecanum_plugins_pidConfigStatics
  {
    friend class gazebo_mecanum_plugins_pidConfig;

    gazebo_mecanum_plugins_pidConfigStatics()
    {
gazebo_mecanum_plugins_pidConfig::GroupDescription<gazebo_mecanum_plugins_pidConfig::DEFAULT, gazebo_mecanum_plugins_pidConfig> Default("Default", "", 0, 0, true, &gazebo_mecanum_plugins_pidConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LEFT_REAR_P = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LEFT_REAR_P = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LEFT_REAR_P = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_REAR_P", "double", 0, "LEFT_REAR wheel PID Controller P parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_REAR_P)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_REAR_P", "double", 0, "LEFT_REAR wheel PID Controller P parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_REAR_P)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LEFT_REAR_I = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LEFT_REAR_I = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LEFT_REAR_I = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_REAR_I", "double", 0, "LEFT_REAR wheel PID Controller I parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_REAR_I)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_REAR_I", "double", 0, "LEFT_REAR wheel PID Controller I parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_REAR_I)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LEFT_REAR_D = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LEFT_REAR_D = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LEFT_REAR_D = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_REAR_D", "double", 0, "LEFT_REAR wheel PID Controller D parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_REAR_D)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_REAR_D", "double", 0, "LEFT_REAR wheel PID Controller D parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_REAR_D)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LEFT_FRONT_P = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LEFT_FRONT_P = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LEFT_FRONT_P = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_FRONT_P", "double", 0, "LEFT_FRONT wheel PID Controller P parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_FRONT_P)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_FRONT_P", "double", 0, "LEFT_FRONT wheel PID Controller P parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_FRONT_P)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LEFT_FRONT_I = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LEFT_FRONT_I = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LEFT_FRONT_I = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_FRONT_I", "double", 0, "LEFT_FRONT wheel PID Controller I parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_FRONT_I)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_FRONT_I", "double", 0, "LEFT_FRONT wheel PID Controller I parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_FRONT_I)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LEFT_FRONT_D = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LEFT_FRONT_D = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LEFT_FRONT_D = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_FRONT_D", "double", 0, "LEFT_FRONT wheel PID Controller D parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_FRONT_D)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("LEFT_FRONT_D", "double", 0, "LEFT_FRONT wheel PID Controller D parameter", "", &gazebo_mecanum_plugins_pidConfig::LEFT_FRONT_D)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RIGHT_FRONT_P = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RIGHT_FRONT_P = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RIGHT_FRONT_P = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_FRONT_P", "double", 0, "RIGHT_FRONT wheel PID Controller P parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_FRONT_P)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_FRONT_P", "double", 0, "RIGHT_FRONT wheel PID Controller P parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_FRONT_P)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RIGHT_FRONT_I = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RIGHT_FRONT_I = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RIGHT_FRONT_I = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_FRONT_I", "double", 0, "RIGHT_FRONT wheel PID Controller I parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_FRONT_I)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_FRONT_I", "double", 0, "RIGHT_FRONT wheel PID Controller I parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_FRONT_I)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RIGHT_FRONT_D = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RIGHT_FRONT_D = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RIGHT_FRONT_D = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_FRONT_D", "double", 0, "RIGHT_FRONT wheel PID Controller D parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_FRONT_D)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_FRONT_D", "double", 0, "RIGHT_FRONT wheel PID Controller D parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_FRONT_D)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RIGHT_REAR_P = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RIGHT_REAR_P = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RIGHT_REAR_P = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_REAR_P", "double", 0, "RIGHT_REAR wheel PID Controller P parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_REAR_P)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_REAR_P", "double", 0, "RIGHT_REAR wheel PID Controller P parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_REAR_P)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RIGHT_REAR_I = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RIGHT_REAR_I = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RIGHT_REAR_I = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_REAR_I", "double", 0, "RIGHT_REAR wheel PID Controller I parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_REAR_I)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_REAR_I", "double", 0, "RIGHT_REAR wheel PID Controller I parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_REAR_I)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RIGHT_REAR_D = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RIGHT_REAR_D = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RIGHT_REAR_D = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_REAR_D", "double", 0, "RIGHT_REAR wheel PID Controller D parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_REAR_D)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::ParamDescription<double>("RIGHT_REAR_D", "double", 0, "RIGHT_REAR wheel PID Controller D parameter", "", &gazebo_mecanum_plugins_pidConfig::RIGHT_REAR_D)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(gazebo_mecanum_plugins_pidConfig::AbstractGroupDescriptionConstPtr(new gazebo_mecanum_plugins_pidConfig::GroupDescription<gazebo_mecanum_plugins_pidConfig::DEFAULT, gazebo_mecanum_plugins_pidConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<gazebo_mecanum_plugins_pidConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<gazebo_mecanum_plugins_pidConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    gazebo_mecanum_plugins_pidConfig __max__;
    gazebo_mecanum_plugins_pidConfig __min__;
    gazebo_mecanum_plugins_pidConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const gazebo_mecanum_plugins_pidConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static gazebo_mecanum_plugins_pidConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &gazebo_mecanum_plugins_pidConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const gazebo_mecanum_plugins_pidConfig &gazebo_mecanum_plugins_pidConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const gazebo_mecanum_plugins_pidConfig &gazebo_mecanum_plugins_pidConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const gazebo_mecanum_plugins_pidConfig &gazebo_mecanum_plugins_pidConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<gazebo_mecanum_plugins_pidConfig::AbstractParamDescriptionConstPtr> &gazebo_mecanum_plugins_pidConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<gazebo_mecanum_plugins_pidConfig::AbstractGroupDescriptionConstPtr> &gazebo_mecanum_plugins_pidConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const gazebo_mecanum_plugins_pidConfigStatics *gazebo_mecanum_plugins_pidConfig::__get_statics__()
  {
    const static gazebo_mecanum_plugins_pidConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = gazebo_mecanum_plugins_pidConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __GAZEBO_MECANUM_PLUGINS_PIDRECONFIGURATOR_H__
